//! Headless browser rendering for SPA (Vue/React/Angular) sites.
//!
//! Traditional crawling fetches raw HTML and parses `<a href>` links.
//! SPA sites ship a bare `<div id="app">` shell — the actual content is
//! generated by JavaScript at runtime. This module drives a headless
//! Chromium to execute that JS, capture the fully-rendered DOM, and
//! intercept every network request the browser makes (JS chunks, CSS,
//! images, fonts, API calls) so we can download them for offline use.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use anyhow::{anyhow, Result};
use futures::StreamExt;
use tokio::sync::Mutex;
use url::Url;

use chromiumoxide::browser::{Browser, BrowserConfig};
use chromiumoxide::cdp::browser_protocol::network::EventRequestWillBeSent;
use chromiumoxide::detection;

/// Maximum time to wait for a page to finish loading + JS execution.
const RENDER_TIMEOUT: Duration = Duration::from_secs(30);
/// Extra settle time after `networkidle` for lazy-loading / AJAX.
const SETTLE_DELAY: Duration = Duration::from_millis(1500);

/// Result of rendering one URL.
pub struct RenderResult {
    /// Fully rendered HTML (post-JS execution) — what you'd see in DevTools.
    pub html: String,
    /// Every URL the browser requested while loading this page
    /// (JS, CSS, images, fonts, XHR/fetch, etc.) — same-domain only.
    pub resource_urls: Vec<Url>,
    /// Internal navigation links (`<a href>`) found in the rendered DOM.
    pub links: Vec<Url>,
    /// Final URL after any redirects.
    pub final_url: Url,
}

/// Locate a Chromium/Chrome binary across all platforms.
///
/// Resolution order:
/// 1. `$CHROME` environment variable (explicit user override)
/// 2. chromiumoxide's built-in detection (uses the `which` crate)
/// 3. Hardcoded fallback paths for Linux / macOS / Windows
fn find_browser() -> Result<PathBuf> {
    // 1. Explicit env override
    if let Ok(p) = std::env::var("CHROME") {
        let path = PathBuf::from(&p);
        if path.exists() {
            return Ok(path);
        }
        return Err(anyhow!("$CHROME points to '{p}' which does not exist"));
    }

    // 2. chromiumoxide auto-detection (PATH lookup via `which`)
    if let Ok(path) = detection::default_executable(detection::DetectionOptions::default()) {
        return Ok(path);
    }

    // 3. Platform fallback paths
    let candidates: &[&str] = &[
        // ---- Linux ----
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable",
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/snap/bin/chromium",
        // ---- macOS ----
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        // ---- Windows ----
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    ];

    for c in candidates {
        if std::path::Path::new(c).exists() {
            return Ok(PathBuf::from(c));
        }
    }

    Err(anyhow!(
        "No Chrome/Chromium/Edge browser found.\n  \
         Install one, or set the CHROME environment variable to its path."
    ))
}

/// Build a headless browser configuration.
fn build_config() -> Result<BrowserConfig> {
    let exec = find_browser()?;
    BrowserConfig::builder()
        .chrome_executable(exec)
        .arg("--no-sandbox")
        .arg("--disable-gpu")
        .arg("--disable-dev-shm-usage")
        .arg("--disable-extensions")
        .arg("--disable-background-networking")
        .window_size(1280, 800)
        .build()
        .map_err(|e| anyhow!("Failed to build browser config: {e}"))
}

/// Launch a headless browser asynchronously.
///
/// Returns `(Browser, handler)`. Spawn the handler immediately on a task:
/// ```ignore
/// let (browser, mut handler) = renderer::launch_browser_async().await?;
/// tokio::spawn(async move { while let Some(_h) = handler.next().await {} });
/// ```
pub async fn launch_browser_async() -> Result<(Browser, chromiumoxide::handler::Handler)> {
    let config = build_config()?;
    Browser::launch(config)
        .await
        .map_err(|e| anyhow!("Failed to launch browser: {e}"))
}

/// Render a single URL: navigate, execute JS, capture HTML + network requests.
///
/// - `base_host`: the normalized (www-stripped) host; only same-domain
///   resource URLs are collected.
/// - `wait_ms`: extra milliseconds to wait after load (for AJAX / lazy images).
pub async fn render_page(
    browser: &Browser,
    url: &Url,
    base_host: &str,
    wait_ms: u64,
) -> Result<RenderResult> {
    // Open a blank page first so we can register the network listener
    // *before* navigation — otherwise we miss the initial resource requests.
    let page = browser
        .new_page("about:blank")
        .await
        .map_err(|e| anyhow!("Failed to open page: {e}"))?;

    // Collect every request URL the browser emits.
    let collected: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
    let collector = Arc::clone(&collected);

    let mut listener = page
        .event_listener::<EventRequestWillBeSent>()
        .await
        .map_err(|e| anyhow!("Failed to attach network listener: {e}"))?;

    let listener_handle = tokio::spawn(async move {
        while let Some(ev) = listener.next().await {
            collector.lock().await.push(ev.request.url.clone());
        }
    });

    let goto_result = tokio::time::timeout(
        RENDER_TIMEOUT,
        page.goto(url.as_str()),
    )
    .await;

    match goto_result {
        Ok(Ok(_)) => {}
        Ok(Err(e)) => {
            listener_handle.abort();
            let _ = page.close().await;
            return Err(anyhow!("Navigation failed for {url}: {e}"));
        }
        Err(_) => {
            listener_handle.abort();
            let _ = page.close().await;
            return Err(anyhow!("Timeout loading {url} after {:?}", RENDER_TIMEOUT));
        }
    }

    // Wait for the page to settle (JS hydration, AJAX, lazy images).
    let settle = Duration::from_millis(wait_ms.max(SETTLE_DELAY.as_millis() as u64));
    tokio::time::sleep(settle).await;

    // Try to detect network idle: wait until no requests for 500ms.
    // We poll the collector; if no new URLs arrive in 500ms, consider it idle.
    let mut prev_count = collected.lock().await.len();
    for _ in 0..20 {
        tokio::time::sleep(Duration::from_millis(500)).await;
        let cur = collected.lock().await.len();
        if cur == prev_count {
            break;
        }
        prev_count = cur;
    }

    // Grab the fully rendered HTML.
    let html = page
        .content()
        .await
        .map_err(|e| anyhow!("Failed to read page content: {e}"))?;

    // Read the final URL (after redirects).
    let final_url = page
        .evaluate("window.location.href")
        .await
        .ok()
        .and_then(|v| v.into_value::<String>().ok())
        .and_then(|s| Url::parse(&s).ok())
        .unwrap_or_else(|| url.clone());

    // Stop the listener before we drain.
    listener_handle.abort();

    // No longer needed: close the page.
    let _ = page.close().await;

    // Extract same-domain resource URLs (deduplicated).
    let mut resource_urls: Vec<Url> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    {
        let guard = collected.lock().await;
        for raw in guard.iter() {
            if let Ok(parsed) = Url::parse(raw) {
                let no_frag = {
                    let mut u = parsed.clone();
                    u.set_fragment(None);
                    u
                };
                let key = no_frag.to_string();
                if seen.insert(key) && crate::crawler::is_same_domain(&no_frag, base_host) {
                    resource_urls.push(no_frag);
                }
            }
        }
    }

    // Extract internal links from the rendered DOM.
    let links = extract_links(&html, &final_url, base_host);

    Ok(RenderResult {
        html,
        resource_urls,
        links,
        final_url,
    })
}

/// Parse rendered HTML and return same-domain navigation links.
///
/// This mirrors the logic in `crawler::extract_urls` but operates on the
/// rendered (post-JS) HTML rather than raw server HTML.
fn extract_links(html: &str, base: &Url, base_host: &str) -> Vec<Url> {
    use scraper::{Html, Selector};

    let doc = Html::parse_document(html);
    let mut urls = Vec::new();

    let selectors = ["a[href]", "area[href]"];
    for sel_str in &selectors {
        if let Ok(sel) = Selector::parse(sel_str) {
            for elem in doc.select(&sel) {
                if let Some(href) = elem.value().attr("href") {
                    if let Some(abs) = crate::crawler::resolve_url(base, href) {
                        if crate::crawler::is_same_domain(&abs, base_host) {
                            urls.push(abs);
                        }
                    }
                }
            }
        }
    }

    urls
}

/// Heuristic: does this raw (un-rendered) HTML look like a SPA shell?
///
/// Indicators:
/// - Very little visible body text (< 200 chars of visible content)
/// - Presence of `#app` / `#root` / `[data-v-app]` mount points
/// - At least one `<script src=...>` (the JS bundle)
#[allow(dead_code)]
pub fn looks_like_spa(html: &str) -> bool {
    let lower = html.to_lowercase();

    // App mount points
    let has_mount = lower.contains(r#"id="app""#)
        || lower.contains(r#"id='app'"#)
        || lower.contains(r#"id="root""#)
        || lower.contains(r#"id='root'"#)
        || lower.contains(r#"id="__nuxt""#)
        || lower.contains(r#"data-v-app"#);

    // Needs a script bundle to qualify
    let has_script = lower.contains("<script");

    // Estimate visible text: strip tags naively
    let text_len = strip_tags(&lower).chars().filter(|c| !c.is_whitespace()).count();

    has_mount && has_script && text_len < 200
}

/// Naively strip HTML tags to estimate visible text length.
fn strip_tags(html: &str) -> String {
    let mut out = String::with_capacity(html.len());
    let mut in_tag = false;
    for ch in html.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(ch),
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_looks_like_spa_vue() {
        let html = r#"<!DOCTYPE html>
        <html><head><title>App</title></head>
        <body><div id="app"></div>
        <script src="/assets/index.abc123.js"></script>
        </body></html>"#;
        assert!(looks_like_spa(html));
    }

    #[test]
    fn test_looks_like_spa_react() {
        let html = r#"<!DOCTYPE html>
        <html><head><title>React App</title></head>
        <body><div id="root"></div>
        <script src="/static/js/main.chunk.js"></script>
        </body></html>"#;
        assert!(looks_like_spa(html));
    }

    #[test]
    fn test_not_spa_traditional() {
        let html = r#"<!DOCTYPE html>
        <html><head><title>Welcome</title></head>
        <body><h1>Hello World</h1>
        <p>This is a traditional page with lots of visible text content
        that is rendered on the server side without any JavaScript framework.</p>
        </body></html>"#;
        assert!(!looks_like_spa(html));
    }

    #[test]
    fn test_find_browser_env() {
        // Just ensure the function logic doesn't panic with an invalid env var.
        std::env::set_var("CHROME", "/nonexistent/path/test-browser-12345");
        assert!(find_browser().is_err() || find_browser().is_ok());
        std::env::remove_var("CHROME");
    }
}
